### PR TITLE
Fixed Margin Between Login and Navbar

### LINKED ISSUE #100: [BUG] Margin Between Navbar And SignIn Is Large
### Verify this issue hasn't been reported before

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### What

The margin between the login/signup form is large it will be good if its reduced 

### Steps to Reproduce

Go to Sign in and here is the image 
Screenshot 2024-10-11 165300

### Screenshots

Before :- 
Screenshot 2024-10-11 165300
 
After :-
Screenshot 2024-10-11 165403

### Do you want to work on this issue?

Yes

### PR DESCRIPTION
**Pull request by ppranay20**
Fixed #100 

This pr fixed the gap between margin and navbar.
Screenshot 2024-10-11 165403

### CODE REVIEW

File: src/app/page.tsx [hunk 1]
```diff
@@ -14,6 +14,7 @@ import {
   Shield,
 } from "lucide-react";
 
+
```
Comment (manuelalferez) [inline src/app/page.tsx:17]:
```suggestion
```

**Review by manuelalferez — APPROVED** [review]
Nice adjustments!
